# Generated by Django 3.2 on 2021-05-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['created'], 'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
    ]
