# Generated by Django 3.2 on 2021-05-10 16:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_alter_paciente_historia_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historia_clinica',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
