# Generated by Django 3.2 on 2021-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_paciente_historia_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historia_clinica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
