# Generated by Django 3.2 on 2021-05-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_alter_paciente_historia_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='emergencia',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicacion',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tratamiento_medico',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
