# Generated by Django 5.0.1 on 2024-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_auto_20210514_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
