# Generated by Django 5.0.4 on 2024-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_alter_paciente_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='emergencia',
            new_name='aseguradora',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='historia_clinica',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tratamiento_medico',
        ),
        migrations.AddField(
            model_name='paciente',
            name='RH',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='condicionSalud',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupoRiesgo',
            field=models.CharField(default=0, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupoSanguineo',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='numDocumento',
            field=models.CharField(default=0, max_length=15, verbose_name='numDocumento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='regimen',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefonoDos',
            field=models.CharField(default=0, max_length=20, verbose_name='telefonoDos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipoAfiliacion',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipoId',
            field=models.CharField(default=0, max_length=50, verbose_name='tipoId'),
            preserve_default=False,
        ),
    ]
