# Generated by Django 3.2 on 2021-05-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_options'),
        ('tratamiento', '0003_auto_20210503_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
