# Generated by Django 3.2 on 2021-05-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0005_auto_20210504_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='radiografias/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='imagenes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamiento.radiografia'),
        ),
    ]
