# Generated by Django 3.2 on 2021-05-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0006_auto_20210504_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
