# Generated by Django 3.2 on 2021-05-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0007_tratamiento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='pieza',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
