# Generated by Django 3.2 on 2021-05-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0008_tratamiento_pieza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='pieza',
            field=models.CharField(max_length=50),
        ),
    ]
