# Generated by Django 3.2 on 2021-05-06 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0010_auto_20210505_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiografia',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='radiografias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tratamiento.radiografia'),
            preserve_default=False,
        ),
    ]
