# Generated by Django 3.2 on 2021-05-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0013_alter_tratamiento_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
