# Generated by Django 5.0.4 on 2024-07-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEUMOCON',
            fields=[
                ('PACIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paciente.paciente')),
                ('LABORATORIO', models.CharField(max_length=25, verbose_name='labo')),
                ('LOTE', models.CharField(max_length=20, verbose_name='lote')),
                ('FECHAVENVACU', models.CharField(max_length=25, verbose_name='fechavenvacun')),
                ('TACTIVAVACU', models.CharField(max_length=25, verbose_name='tacticavacun')),
                ('FECHAAPLI', models.CharField(max_length=25, verbose_name='fechaaplica')),
                ('FECHAPROX', models.CharField(max_length=25, verbose_name='fechaproxivacun')),
                ('EMPRESA', models.CharField(max_length=30, verbose_name='nombrempresa')),
                ('CONDICIONUSUARIA', models.CharField(max_length=30, verbose_name='condicionusuario')),
                ('NOMBREVACUNADOR', models.CharField(max_length=30, verbose_name='nombrevacunadora')),
                ('NUMFACTURA', models.CharField(max_length=30, verbose_name='numfactu')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacunasPacientes',
            fields=[
                ('PACIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paciente.paciente')),
                ('DPT_ACELULAR', models.CharField(default='no', max_length=50, verbose_name='DPT')),
                ('NEUMOCOCO_CONJUGADO', models.CharField(default='no', max_length=50, verbose_name='NEUMOCON')),
                ('MENINGOCOCO', models.CharField(default='no', max_length=50, verbose_name='MENINGO')),
                ('TRIPLE_VIRAL', models.CharField(default='no', max_length=50, verbose_name='TRIPLEVIRAL')),
                ('VARICELA', models.CharField(default='no', max_length=50, verbose_name='VARICELA')),
                ('HEPATITIS_A', models.CharField(default='no', max_length=50, verbose_name='HA')),
                ('FIEBRE_AMARILLA', models.CharField(default='no', max_length=50, verbose_name='FIEBREAMARILLA')),
                ('INFLUENZA', models.CharField(default='no', max_length=50, verbose_name='INFLUENZA')),
                ('COVID', models.CharField(default='no', max_length=50, verbose_name='COVID')),
                ('HERPES_ZOSTER', models.CharField(default='no', max_length=50, verbose_name='HERPES')),
                ('HEPATITIS_B', models.CharField(default='no', max_length=50, verbose_name='HB')),
                ('ANTIRRABICA', models.CharField(default='no', max_length=50, verbose_name='ANTIRRABICA')),
                ('VPH', models.CharField(default='no', max_length=50, verbose_name='VPH')),
                ('HA_HB', models.CharField(default='no', max_length=50, verbose_name='HAHB')),
                ('TETANO_ANTITETANICA', models.CharField(default='no', max_length=50, verbose_name='TETANO')),
                ('TETANO_DIFTERICO', models.CharField(default='no', max_length=50, verbose_name='TETANODIFTERICO')),
                ('FIEBRE_TIFOIDEA', models.CharField(default='no', max_length=50, verbose_name='FIEBRETIFOIDEA')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
