# Generated by Django 5.0.4 on 2024-05-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_rename_rh_paciente_rh_and_more'),
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunaspacientes',
            name='id',
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='PACIENTE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paciente.paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='ANTIRRABICA',
            field=models.CharField(default='no', max_length=50, verbose_name='ANTIRRABICA'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='COVID',
            field=models.CharField(default='no', max_length=50, verbose_name='COVID'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR',
            field=models.CharField(default='no', max_length=50, verbose_name='DPT'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='FIEBRE_AMARILLA',
            field=models.CharField(default='no', max_length=50, verbose_name='FIEBREAMARILLA'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='FIEBRE_TIFOIDEA',
            field=models.CharField(default='no', max_length=50, verbose_name='FIEBRETIFOIDEA'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='HA_HB',
            field=models.CharField(default='no', max_length=50, verbose_name='HAHB'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='HEPATITIS_A',
            field=models.CharField(default='no', max_length=50, verbose_name='HA'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='HEPATITIS_B',
            field=models.CharField(default='no', max_length=50, verbose_name='HB'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='HERPES_ZOSTER',
            field=models.CharField(default='no', max_length=50, verbose_name='HERPES'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='INFLUENZA',
            field=models.CharField(default='no', max_length=50, verbose_name='INFLUENZA'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='MENINGOCOCO',
            field=models.CharField(default='no', max_length=50, verbose_name='MENINGO'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='NEUMOCOCO_CONJUGADO',
            field=models.CharField(default='no', max_length=50, verbose_name='NEUMOCON'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='TETANO_ANTITETANICA',
            field=models.CharField(default='no', max_length=50, verbose_name='TETANO'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='TETANO_DIFTERICO',
            field=models.CharField(default='no', max_length=50, verbose_name='TETANODIFTERICO'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='TRIPLE_VIRAL',
            field=models.CharField(default='no', max_length=50, verbose_name='TRIPLEVIRAL'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='VARICELA',
            field=models.CharField(default='no', max_length=50, verbose_name='VARICELA'),
        ),
        migrations.AlterField(
            model_name='vacunaspacientes',
            name='VPH',
            field=models.CharField(default='no', max_length=50, verbose_name='VPH'),
        ),
    ]
