# Generated by Django 5.0.7 on 2024-07-30 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANTIRRABICA_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='ANTIRRABICA_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='ANTIRRABICA_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='ANTIRRABICA_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='ANTIRRABICA_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='ANTIRRABICA_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='ANTIRRABICA_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='ANTIRRABICA_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='ANTIRRABICA_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='COVID_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='COVID_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='COVID_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='COVID_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='COVID_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='COVID_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='COVID_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='COVID_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='COVID_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='DPT_ACELULAR_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='DPT_ACELULAR_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='DPT_ACELULAR_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='DPT_ACELULAR_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='DPT_ACELULAR_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='DPT_ACELULAR_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='DPT_ACELULAR_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='DPT_ACELULAR_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='DPT_ACELULAR_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_AMARILLA_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_AMARILLA_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_AMARILLA_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_AMARILLA_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_AMARILLA_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_AMARILLA_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_AMARILLA_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_AMARILLA_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_AMARILLA_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_TIFOIDEA_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_TIFOIDEA_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_TIFOIDEA_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_TIFOIDEA_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_TIFOIDEA_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_TIFOIDEA_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_TIFOIDEA_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_TIFOIDEA_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='FIEBRE_TIFOIDEA_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HA_HB_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HA_HB_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HA_HB_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HA_HB_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HA_HB_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HA_HB_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HA_HB_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HA_HB_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HA_HB_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_A_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_A_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_A_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_A_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_A_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_A_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_A_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_A_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_A_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_B_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_B_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_B_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_B_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_B_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_B_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_B_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_B_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HEPATITIS_B_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HERPES_ZOSTER_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HERPES_ZOSTER_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HERPES_ZOSTER_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HERPES_ZOSTER_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HERPES_ZOSTER_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HERPES_ZOSTER_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HERPES_ZOSTER_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HERPES_ZOSTER_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='HERPES_ZOSTER_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='INFLUENZA_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='INFLUENZA_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='INFLUENZA_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='INFLUENZA_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='INFLUENZA_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='INFLUENZA_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='INFLUENZA_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='INFLUENZA_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='INFLUENZA_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='MENINGOCOCO_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='MENINGOCOCO_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='MENINGOCOCO_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='MENINGOCOCO_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='MENINGOCOCO_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='MENINGOCOCO_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='MENINGOCOCO_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='MENINGOCOCO_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='MENINGOCOCO_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_ANTITETANICA_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_ANTITETANICA_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_ANTITETANICA_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_ANTITETANICA_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_ANTITETANICA_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_ANTITETANICA_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_ANTITETANICA_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_ANTITETANICA_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_ANTITETANICA_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_DIFTERICO_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_DIFTERICO_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_DIFTERICO_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_DIFTERICO_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_DIFTERICO_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_DIFTERICO_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_DIFTERICO_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_DIFTERICO_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TETANO_DIFTERICO_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TRIPLE_VIRAL_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TRIPLE_VIRAL_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TRIPLE_VIRAL_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TRIPLE_VIRAL_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TRIPLE_VIRAL_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TRIPLE_VIRAL_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TRIPLE_VIRAL_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TRIPLE_VIRAL_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='TRIPLE_VIRAL_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VARICELA_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VARICELA_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VARICELA_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VARICELA_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VARICELA_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VARICELA_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VARICELA_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VARICELA_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VARICELA_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VPH_1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VPH_2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VPH_3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VPH_4',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VPH_5',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VPH_R1',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VPH_R2',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VPH_R3',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
        migrations.CreateModel(
            name='VPH_U',
            fields=[
                ('datoscomunvacun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vacunas.datoscomunvacun')),
            ],
            bases=('vacunas.datoscomunvacun',),
        ),
    ]
