# Generated by Django 5.0.4 on 2024-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neumocon',
            name='FECHAAPLI',
            field=models.DateTimeField(verbose_name='fechaaplica'),
        ),
        migrations.AlterField(
            model_name='neumocon',
            name='FECHAPROX',
            field=models.DateTimeField(verbose_name='fechaproxivacun'),
        ),
        migrations.AlterField(
            model_name='neumocon',
            name='FECHAVENVACU',
            field=models.DateTimeField(verbose_name='fechavenvacun'),
        ),
    ]
