# Generated by Django 5.0.4 on 2024-07-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0002_alter_neumocon_fechaapli_alter_neumocon_fechaprox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neumocon',
            name='NOMBREVACUNADOR',
            field=models.CharField(default='mauro', max_length=30, verbose_name='nombrevacunadora'),
        ),
    ]
