# Generated by Django 5.0.4 on 2024-06-09 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_rename_rh_paciente_rh_and_more'),
        ('vacunas', '0002_remove_vacunaspacientes_id_vacunaspacientes_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEUMOCON',
            fields=[
                ('PACIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paciente.paciente')),
                ('VACUNA', models.CharField(max_length=25, verbose_name='vacuna')),
                ('LABORATORIO', models.CharField(max_length=25, verbose_name='laboratorio')),
                ('LOTE', models.CharField(max_length=20, verbose_name='lote')),
                ('FECHAAPLI', models.DateField()),
                ('FECHAPROX', models.DateField()),
                ('NUMFACTURA', models.CharField(max_length=30, verbose_name='numfactura')),
            ],
        ),
    ]
