# Generated by Django 5.0.7 on 2024-07-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0002_antirrabica_1_antirrabica_2_antirrabica_3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DPT_ACELULAR_R2',
            new_name='T_DPT_ACELULAR_1',
        ),
        migrations.RenameModel(
            old_name='DPT_ACELULAR_2',
            new_name='T_DPT_ACELULAR_2',
        ),
        migrations.RenameModel(
            old_name='DPT_ACELULAR_4',
            new_name='T_DPT_ACELULAR_3',
        ),
        migrations.RenameModel(
            old_name='DPT_ACELULAR_U',
            new_name='T_DPT_ACELULAR_4',
        ),
        migrations.RenameModel(
            old_name='DPT_ACELULAR_5',
            new_name='T_DPT_ACELULAR_5',
        ),
        migrations.RenameModel(
            old_name='DPT_ACELULAR_R1',
            new_name='T_DPT_ACELULAR_R1',
        ),
        migrations.RenameModel(
            old_name='DPT_ACELULAR_3',
            new_name='T_DPT_ACELULAR_R2',
        ),
        migrations.RenameModel(
            old_name='DPT_ACELULAR_R3',
            new_name='T_DPT_ACELULAR_R3',
        ),
        migrations.RenameModel(
            old_name='DPT_ACELULAR_1',
            new_name='T_DPT_ACELULAR_U',
        ),
    ]
