# Generated by Django 5.0.4 on 2024-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0003_alter_neumocon_nombrevacunador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neumocon',
            name='NOMBREVACUNADOR',
            field=models.CharField(max_length=30, verbose_name='nombrevacunadora'),
        ),
    ]
