# Generated by Django 5.0.4 on 2024-07-19 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0003_neumocon'),
    ]

    operations = [
        migrations.AddField(
            model_name='neumocon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neumocon',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='neumocon',
            name='VACUNA',
            field=models.CharField(default='Neumocon', max_length=25, verbose_name='vacuna'),
        ),
    ]
