# Generated by Django 5.0.4 on 2024-07-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0004_alter_neumocon_nombrevacunador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR',
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR_1',
            field=models.CharField(default='no', max_length=50, verbose_name='DPT1'),
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR_1R',
            field=models.CharField(default='no', max_length=50, verbose_name='DPTR1'),
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR_2',
            field=models.CharField(default='no', max_length=50, verbose_name='DPT2'),
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR_2R',
            field=models.CharField(default='no', max_length=50, verbose_name='DPTR2'),
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR_3',
            field=models.CharField(default='no', max_length=50, verbose_name='DPT3'),
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR_3R',
            field=models.CharField(default='no', max_length=50, verbose_name='DPTR3'),
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR_4',
            field=models.CharField(default='no', max_length=50, verbose_name='DPT4'),
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR_5',
            field=models.CharField(default='no', max_length=50, verbose_name='DPT5'),
        ),
        migrations.AddField(
            model_name='vacunaspacientes',
            name='DPT_ACELULAR_U',
            field=models.CharField(default='no', max_length=50, verbose_name='DPTU'),
        ),
    ]
